# Generated by Django 2.2 on 2020-03-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('grant', models.BooleanField(default=False)),
                ('liked_by', models.ManyToManyField(related_name='liked', to='wish.User')),
                ('wished_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='wish.User')),
            ],
        ),
    ]
