# Generated by Django 2.2 on 2020-03-20 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
